<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>host.fairy</groupId>
    <artifactId>visual</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>visual-bootstrap</module>
        <module>visual-web</module>
        <module>visual-service</module>
        <module>visual-model</module>
        <module>visual-mapper</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- dependence -->
        <spring.boot.version>3.5.8</spring.boot.version>
        <mybatis.spring.boot.version>4.0.0</mybatis.spring.boot.version>
        <!-- custom dependence -->
        <java.fairylandfuture.version>1.0.0</java.fairylandfuture.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis.spring.boot.version}</version>
            </dependency>

            <dependency>
                <groupId>host.fairy</groupId>
                <artifactId>java-fairylandfuture</artifactId>
                <version>${java.fairylandfuture.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
